---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/ethscriptions/{id}/data":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: data ethscription
      responses:
        '200':
          description: successful
  "/ethscriptions/newer_ethscriptions":
    get:
      summary: newer_ethscriptions ethscription
      responses:
        '200':
          description: successful
  "/ethscriptions/{id}/attachment":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: attachment ethscription
      responses:
        '200':
          description: successful
  "/ethscriptions":
    get:
      summary: list ethscriptions
      responses:
        '200':
          description: successful
  "/ethscriptions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show ethscription
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
